
import React from 'react';
import { AnalysisResult, RiskLevel } from '../types';

interface RiskAssessmentProps {
  result: AnalysisResult | null;
}

const RiskAssessment: React.FC<RiskAssessmentProps> = ({ result }) => {
  if (!result) {
    return (
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex items-center justify-center h-full min-h-[300px]">
        <div className="text-center">
            <div className="text-gray-400 mb-4">
                <svg className="w-16 h-16 mx-auto opacity-20" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                </svg>
            </div>
            <p className="text-gray-500">Submit a reading to see AI intelligence report.</p>
        </div>
      </div>
    );
  }

  const riskColors = {
    [RiskLevel.LOW]: 'bg-green-100 text-green-800 border-green-200',
    [RiskLevel.MEDIUM]: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    [RiskLevel.HIGH]: 'bg-red-100 text-red-800 border-red-200'
  };

  const riskLabels = {
    [RiskLevel.LOW]: 'Low Risk',
    [RiskLevel.MEDIUM]: 'Medium Risk',
    [RiskLevel.HIGH]: 'High Risk'
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 animate-fadeIn">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-xl font-bold text-gray-800">Intelligence Report</h3>
        <span className={`px-4 py-1 rounded-full text-sm font-bold border ${riskColors[result.riskLevel]}`}>
          {riskLabels[result.riskLevel]}
        </span>
      </div>

      <div className="space-y-6">
        <div>
          <h4 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Summary</h4>
          <p className="text-gray-700 leading-relaxed">{result.summary}</p>
        </div>

        {result.anomalies.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Anomaly Detection</h4>
            <div className="flex flex-wrap gap-2">
              {result.anomalies.map((anomaly, idx) => (
                <span key={idx} className="bg-red-50 text-red-700 px-3 py-1 rounded-lg text-xs font-medium border border-red-100">
                  ⚠️ {anomaly}
                </span>
              ))}
            </div>
          </div>
        )}

        <div>
          <h4 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Health Recommendations</h4>
          <ul className="space-y-2">
            {result.recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start">
                <span className="flex-shrink-0 w-5 h-5 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs mr-3 mt-0.5">✓</span>
                <span className="text-gray-600 text-sm">{rec}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="pt-4 border-t border-gray-100 text-[10px] text-gray-400 uppercase font-medium">
            Academic Project Disclaimer: This report is generated by an AI model for educational purposes and does not constitute professional medical advice.
        </div>
      </div>
    </div>
  );
};

export default RiskAssessment;
